### ISSUE TITLE
大佬， 帮忙看看这是为什么？ TypeError: Cannot read property 'loaded' of null

### ISSUE THREAD

**Issue by guofeng321** [yllg/mpvue-xbyjShop#15]
安装完依赖后 npm run dev 就报这个错误
internal/modules/cjs/loader.js:730
    if (!cachedModule.loaded) {
                      ^

TypeError: Cannot read property 'loaded' of null
    at Function.Module._load (internal/modules/cjs/loader.js:730:23)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at parsePages (C:\Users\feng\my\mpvue-xbyjShop-master\mpvue-xbyjShop-master\buyer\node_modules\_mpvue-entry@1.5.9@mpvue-entry\lib\parser.js:45:17)
    at Function.getEntry (C:\Users\feng\my\mpvue-xbyjShop-master\mpvue-xbyjShop-master\buyer\node_modules\_mpvue-entry@1.5.9@mpvue-entry\lib\index.js:25:13)
    at Object.<anonymous> (C:\Users\feng\my\mpvue-xbyjShop-master\mpvue-xbyjShop-master\buyer\build\webpack.base.conf.js:13:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

**Comment by yanglanping** [comment]
> 安装完依赖后 npm run dev 就报这个错误 internal/modules/cjs/loader.js：730 if （！cachedModule.loaded） { ^
> 
> TypeError：无法读取 Function.Module._load （internal/modules/cjs/loader.js：730：23） at Module.require （internal/modules/cjs/loader.js：952：19） at require （internal/modules/cjs/helpers.js：88：18） at parsePages （C：\Users\feng\my\mpvue-xbyjShop-master\mpvue-xbyjShop-master\buyer\node_modules_mpvue-entry@[1.5.9@mpvue-entry](mailto:1.5.9@mpvue-entry)\lib\parser.js：45：17） 的 null 属性“loaded”在 Function.getEntry （C：\Users\feng\my\mpvue-xbyjShop-master\mpvue-xbyjShop-master\buyer\[node_modules_mpvue-entry@1.5.9@mpvue-entry](mailto:1.5.9@mpvue-entry)\lib\index.js：25：13） 在对象。（C：\Users\feng\my\mpvue-xbyjShop-master\mpvue-xbyjShop-master\buyer\build\webpack.base.conf.js：13：26）在 Module._compile （internal/modules/cjs/loader.js：1063：30） 在 Module.load （internal/modules/cjs/loader.js：928：32） 在 Function.Module._load （internal/modules/cjs/loader.js：769：14）

metoo
